In [1]:
import numpy as np
import tensorflow as tf
import random as rn

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [ ]:
import os 
os.environ['PYTHONHASHSEED'] = '0'

In [2]:
np.random.seed(39)
rn.seed(1356)
tf.random.set_seed(68)

In [3]:
#Bias thing
from keras.models import Sequential
from keras.layers import Dense, Activation


In [5]:
model = Sequential([
    Dense(4, input_shape=(1,), activation='relu', use_bias = True, bias_initializer = 'zeros'),
    Dense(2, activation='softmax')
])

In [6]:
model.get_weights()

[array([[-0.08024478, -0.02158999,  0.9895737 , -0.9529865 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[ 0.43391132, -0.58386874],
        [ 0.8320174 ,  0.64901996],
        [-0.53872895,  0.87365556],
        [-0.30961037,  0.84594774]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [1]:
os.getcwd()

'/Users/ari/devel/python_projects/machine_learning_project/intro_to_deep_learning'